# Generated by Django 4.2.5 on 2024-03-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('CollegeName', models.CharField(max_length=100)),
                ('BranchOfStudy', models.CharField(max_length=100)),
                ('yearofeducation', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('mobile2', models.CharField(blank=True, max_length=20, null=True)),
                ('insta', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
                ('aadhar_card', models.FileField(upload_to='documents')),
                ('achievement_file', models.FileField(upload_to='documents')),
                ('text_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.textdata')),
            ],
        ),
    ]
