# Generated by Django 4.2.5 on 2024-03-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='statement1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textdata',
            name='statement2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textdata',
            name='statement3',
            field=models.BooleanField(default=False),
        ),
    ]
