# Generated by Django 4.2.5 on 2024-03-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_textdata_statement1_textdata_statement2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='achievement',
            field=models.TextField(blank=True),
        ),
    ]
